# Generated by Django 2.2 on 2020-01-31 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('current_address', models.CharField(max_length=256)),
                ('adhar_no', models.IntegerField()),
                ('police_verfication', models.CharField(max_length=13)),
                ('service_provider', models.CharField(choices=[('maids', 'maids'), ('cook', 'cook'), ('child_care', 'child_care'), ('elder_care', 'elder_care'), ('car_cleaner', 'car_cleaner'), ('driver', 'driver')], max_length=10)),
                ('type', models.CharField(choices=[('24 hours', '24 hours'), ('12 hours', '12 hours'), ('part_time', 'part_time')], max_length=10)),
                ('landlord_address', models.CharField(max_length=100, null=True)),
                ('landlord_number', models.IntegerField()),
                ('landlard_permanetaddress', models.CharField(max_length=100, null=True)),
                ('land_family_no', models.CharField(max_length=13, null=True)),
                ('emergency_no', models.CharField(max_length=13, null=True)),
                ('society_name', models.CharField(max_length=100)),
                ('tower', models.IntegerField()),
                ('flat_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=100)),
                ('sector_area', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('pincode', models.CharField(max_length=6)),
                ('no_of_towers', models.IntegerField()),
                ('tower', models.CharField(max_length=100)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Residents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=13)),
                ('total_family_member', models.CharField(max_length=256)),
                ('flat_no', models.IntegerField()),
                ('flat_type', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('tenat', 'tenat'), ('owner', 'owner')], max_length=10)),
                ('agreement', models.CharField(max_length=100, null=True)),
                ('owner_name', models.CharField(max_length=256, null=True)),
                ('owner_number', models.CharField(max_length=13, null=True)),
                ('id_proof', models.FileField(upload_to='idproof_images')),
                ('city', models.CharField(max_length=256)),
                ('residents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pay_amount', models.CharField(max_length=10)),
                ('mobile_number', models.CharField(max_length=100)),
                ('emp_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_request', to='maid.Employee')),
                ('resident_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_request', to='maid.Residents')),
                ('society_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='society_request', to='maid.Society')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attandance', models.CharField(choices=[('a', 'a'), ('p', 'p')], max_length=10)),
                ('date_fields', models.DateField()),
                ('month', models.CharField(max_length=15)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='maid.Employee')),
            ],
        ),
    ]
